apiVersion: apps/v1

kind: DaemonSet
metadata:
  name: node-exporter

spec:
  selector: 
    matchLabels: 
      app: node-exporter

  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      restartPolicy: Always

      hostNetwork: true

      containers:
        - name: node-exporter
          image: prom/node-exporter:v1.0.0-rc.0
          imagePullPolicy: "Always"
          ports:
            - containerPort: 9100
              hostPort: 9100

          env:
            - name: TZ
              value: America/Recife
